proxy-providers:
  iKuuu:
    type: file
    path: "./providers/iKuuu_V2.yaml"
    interval: 43200
    payload: []
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
  SakuraCat:
    type: file
    path: "./providers/SakuraCat.yaml"
    payload: []
    interval: 43200
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
  CordCloud:
    type: file
    path: "./providers/CordCloud.yaml"
    payload: []
    interval: 43200
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600

proxy-groups:
  - name: 节点选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies: ['自动选择', '香港节点', '台湾节点', '狮城节点', '日本节点', '美国节点', '手动切换', '尊享节点', 'DIRECT']
  - name: 手动切换
    icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 自动选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    use: ['SakuraCat', 'CordCloud']
    exclude-filter: '倍率:(2|1\.)|专线|专用|高级|高倍率|🇨🇳'
    interval: 300
    tolerance: 50
    proxies:
      - DIRECT
  - name: CUHK
    icon: https://cuhk.edu.hk/chinese/images/fav-icons/favicon-32x32.png
    type: select
    proxies: ['节点选择', '香港节点', '尊享节点', 'DIRECT']
  - name: LLM
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies: ['节点选择', '自动选择', '狮城节点', '台湾节点', '日本节点', '美国节点', '手动切换']
  # - name: 奈飞视频
  #   icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
  #   type: select
  #   proxies: ['节点选择', '自动选择', '奈飞节点', '狮城节点', '香港节点', '台湾节点', '日本节点', '美国节点', '手动切换', 'DIRECT']
  # - name: 游戏平台
  #   icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
  #   type: select
  #   proxies: ['DIRECT', '节点选择', '美国节点', '香港节点', '台湾节点', '狮城节点', '日本节点', '手动切换']
  - name: 海外应用
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies: ['DIRECT', '节点选择', '美国节点', '香港节点', '台湾节点', '狮城节点', '日本节点', '手动切换']
  - name: 尊享节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/VIP.png
    type: select
    include-all: true
    exclude-filter: '🇨🇳'
    filter: '(专线|专用|高级|倍消耗)'
  - name: 全球直连
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies: ['DIRECT', '节点选择', '手动切换']
  - name: 广告拦截
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies: ['REJECT', 'DIRECT']
  # - name: 应用净化
  #   icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
  #   type: select
  #   proxies: ['REJECT', 'DIRECT']
  - name: 哔哩哔哩
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies: ['全球直连', '台湾节点', '香港节点', 'DIRECT']
  - name: 漏网之鱼
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies: ['节点选择', '自动选择', 'DIRECT', '香港节点', '台湾节点', '狮城节点', '日本节点', '美国节点', '手动切换']
  - name: 香港节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    # exclude-filter: '倍率:(2|1\.)'
    type: url-test
    interval: 300
    tolerance: 50
  - name: 日本节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    type: url-test
    interval: 300
    tolerance: 50
  - name: 美国节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    type: url-test
    interval: 300
    tolerance: 50
  - name: 台湾节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: url-test
    interval: 300
    tolerance: 50
  - name: 狮城节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: url-test
    interval: 300
    tolerance: 50
  # - name: 奈飞节点
  #   icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
  #   include-all: true
  #   filter: (?i)NF|奈飞|解锁|Netflix|NETFLIX|Media
  #   type: select

rule-providers:
  LocalAreaNetwork:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  MoreAD:
    url: https://raw.githubusercontent.com/dy1an-W/AdBlockList/refs/heads/main/dylan-adBlock.list
    path: ./ruleset/MoreAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleFCM:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SteamCN:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bing:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
    path: ./ruleset/Bing.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OneDrive:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    path: ./ruleset/OneDrive.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  AI:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs"
    interval: 86400
  # NetEaseMusic:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
  #   path: ./ruleset/NetEaseMusic.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Epic:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
  #   path: ./ruleset/Epic.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Origin:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
  #   path: ./ruleset/Origin.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Sony:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
  #   path: ./ruleset/Sony.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Steam:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
  #   path: ./ruleset/Steam.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Nintendo:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
  #   path: ./ruleset/Nintendo.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # YouTube:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
  #   path: ./ruleset/YouTube.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Netflix:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
  #   path: ./ruleset/Netflix.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  # Bahamut:
  #   url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
  #   path: ./ruleset/Bahamut.list
  #   behavior: classical
  #   interval: 86400
  #   format: text
  #   type: http
  BilibiliHMT:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bilibili:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http

rules:
  - "RULE-SET,BanAD,广告拦截"
  - "RULE-SET,BanProgramAD,广告拦截"
  - "RULE-SET,MoreAD,广告拦截"
  - "RULE-SET,AI,LLM"
  - "RULE-SET,LocalAreaNetwork,全球直连"
  - 'DOMAIN,cordc.net,全球直连'
  - 'DOMAIN-SUFFIX,cuhk.edu.hk,CUHK'
  - 'PROCESS-NAME,Mail,DIRECT'
  - 'DOMAIN-SUFFIX,sentry.io,LLM'
  - 'DOMAIN-SUFFIX,chatgpt.com,LLM'
  - 'DOMAIN-SUFFIX,azurefd.net,LLM'
  - 'DOMAIN-SUFFIX,identrust.com,LLM'
  - 'DOMAIN-SUFFIX,challenges.cloudflare.com,LLM'
  - 'DOMAIN-SUFFIX,cdn.usefathom.com,LLM'
  - 'DOMAIN-SUFFIX,anthropic.com,LLM'
  - 'DOMAIN-SUFFIX,claude.ai,LLM'
  - 'DOMAIN,gemini.google.com,LLM'
  - 'DOMAIN-SUFFIX,gemini.com,LLM'
  - 'DOMAIN-SUFFIX,huggingface.co,LLM'
  - 'DOMAIN,ai.google.dev,LLM'
  - 'DOMAIN,alkalimakersuite-pa.clients6.google.com,LLM'
  - 'DOMAIN,makersuite.google.com,LLM'
  - 'DOMAIN-SUFFIX,deepmind.com,LLM'
  - 'DOMAIN-SUFFIX,bard.google.com,LLM'
  - 'DOMAIN-SUFFIX,deepmind.google,LLM'
  - 'DOMAIN-SUFFIX,generativeai.google,LLM'
  - 'DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com,LLM'
  - 'DOMAIN-SUFFIX,apis.google.com,LLM'
  - 'DOMAIN-KEYWORD,colab,LLM'
  - 'DOMAIN-KEYWORD,developerprofiles,LLM'
  - 'DOMAIN-KEYWORD,generativelanguage,LLM'
  - 'DOMAIN-KEYWORD,copilot,LLM'
  - 'DOMAIN-SUFFIX,clients6.google.com,LLM'
  - 'DOMAIN,generativelanguage.googleapis.com,LLM'
  - 'DOMAIN,alkalimakersuite-pa.clients6.google.com,LLM'
  - 'DOMAIN,makersuite.google.com,LLM'
  - 'DOMAIN-SUFFIX,bard.google.com,LLM'
  - 'DOMAIN-SUFFIX,deepmind.com,LLM'
  - 'DOMAIN-SUFFIX,deepmind.google,LLM'
  - 'DOMAIN-SUFFIX,gemini.google.com,LLM'
  - 'DOMAIN-SUFFIX,generativeai.google,LLM'
  - 'DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com,LLM'
  - 'DOMAIN-SUFFIX,apis.google.com,LLM'
  - 'DOMAIN-KEYWORD,colab,LLM'
  - 'DOMAIN-KEYWORD,developerprofiles,LLM'
  - 'DOMAIN-KEYWORD,generativelanguage,LLM'
  - 'DOMAIN-SUFFIX,appstorrent.rum,全球直连'
  - "RULE-SET,UnBan,全球直连"

  - "RULE-SET,GoogleFCM,海外应用"
  - "RULE-SET,GoogleCN,全球直连"
  - "RULE-SET,SteamCN,全球直连"
  - "RULE-SET,Bing,海外应用"
  - "RULE-SET,OneDrive,海外应用"
  - "RULE-SET,Microsoft,海外应用"
  - "RULE-SET,Apple,海外应用"
  - "RULE-SET,Telegram,海外应用"
  # - "RULE-SET,Epic,游戏平台"
  # - "RULE-SET,Origin,游戏平台"
  # - "RULE-SET,Sony,游戏平台"
  # - "RULE-SET,Steam,游戏平台"
  # - "RULE-SET,Nintendo,游戏平台"
  # - "RULE-SET,YouTube,油管视频"
  # - "RULE-SET,Netflix,奈飞视频"
  # - "RULE-SET,Bahamut,巴哈姆特"
  - "RULE-SET,BilibiliHMT,哔哩哔哩"
  - "RULE-SET,Bilibili,哔哩哔哩"
  - "RULE-SET,ProxyGFWlist,海外应用"
  - "RULE-SET,ChinaDomain,全球直连"
  - "RULE-SET,ChinaCompanyIp,全球直连"
  - "RULE-SET,Download,全球直连"
  - "GEOIP,CN,全球直连"
  - "MATCH,漏网之鱼"
