#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${REPO_DIR}/config/clash.template.yaml"
ENV_FILE="${REPO_DIR}/.env"

usage() {
  cat <<'EOF'
Usage:
  scripts/render-clash-config.sh file [output]
  scripts/render-clash-config.sh http [output]

Modes:
  file  Render file-based proxy-providers for local Mihomo caches.
  http  Render http-based proxy-providers from environment variables.

Env:
  FILE_OUTPUT_PATH  Optional default output path for file mode
  HTTP_OUTPUT_PATH  Optional default output path for http mode
  SAKURACAT_URL  Required if SakuraCat should be included
  CORDCLOUD_URL  Required if CordCloud should be included
  IKUUU_URL      Optional
EOF
}

provider_block_common() {
  cat <<'EOF'
    payload: []
    interval: 43200
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
EOF
}

load_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "${ENV_FILE}"
    set +a
  fi
}

render_file_provider() {
  local name="$1"
  local path="$2"
  cat <<EOF
  ${name}:
    type: file
    path: "${path}"
$(provider_block_common)
EOF
}

render_http_provider() {
  local name="$1"
  local path="$2"
  local url="$3"
  cat <<EOF
  ${name}:
    type: http
    url: "${url}"
    path: "${path}"
$(provider_block_common)
EOF
}

render_file_mode() {
  cat <<'EOF'
proxy-providers:
EOF
  render_file_provider "iKuuu" "./providers/iKuuu_V2.yaml"
  render_file_provider "SakuraCat" "./providers/SakuraCat.yaml"
  render_file_provider "CordCloud" "./providers/CordCloud.yaml"
}

render_http_mode() {
  local emitted=0
  cat <<'EOF'
proxy-providers:
EOF

  if [[ -n "${IKUUU_URL:-}" ]]; then
    render_http_provider "iKuuu" "./providers/iKuuu_V2.yaml" "${IKUUU_URL}"
    emitted=1
  fi
  if [[ -n "${SAKURACAT_URL:-}" ]]; then
    render_http_provider "SakuraCat" "./providers/SakuraCat.yaml" "${SAKURACAT_URL}"
    emitted=1
  fi
  if [[ -n "${CORDCLOUD_URL:-}" ]]; then
    render_http_provider "CordCloud" "./providers/CordCloud.yaml" "${CORDCLOUD_URL}"
    emitted=1
  fi

  if [[ "${emitted}" -eq 0 ]]; then
    echo "No provider URLs supplied for http mode." >&2
    exit 1
  fi
}

write_output() {
  local mode="$1"
  local output="$2"
  local resolved_output="$output"

  if [[ "${resolved_output}" != /* ]]; then
    resolved_output="${REPO_DIR}/${resolved_output}"
  fi

  # Write directly to the destination path so a symlink output keeps pointing
  # to the same target file. Do not render via temp file + rename.
  : > "${resolved_output}"
  {
    echo "# Generated by scripts/render-clash-config.sh"
    case "${mode}" in
      file)
        render_file_mode
        ;;
      http)
        load_env_file
        render_http_mode
        ;;
    esac
    echo
    cat "${TEMPLATE}"
  } >> "${resolved_output}"
}

main() {
  local mode="${1:-}"
  local output="${2:-}"

  load_env_file

  if [[ -z "${mode}" ]]; then
    usage >&2
    exit 1
  fi

  case "${mode}" in
    file)
      if [[ -z "${output}" ]]; then
        output="${FILE_OUTPUT_PATH:-}"
      fi
      if [[ -z "${output}" ]]; then
        echo "No output path provided for file mode." >&2
        exit 1
      fi
      write_output "${mode}" "${output}"
      ;;
    http)
      if [[ -z "${output}" ]]; then
        output="${HTTP_OUTPUT_PATH:-}"
      fi
      if [[ -z "${output}" ]]; then
        echo "No output path provided for http mode." >&2
        exit 1
      fi
      write_output "${mode}" "${output}"
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
