#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${REPO_DIR}/config/clash.template.yaml"

usage() {
  cat <<'EOF'
Usage:
  scripts/render-clash-config.sh file <output>
  scripts/render-clash-config.sh http <output>

Modes:
  file  Render file-based proxy-providers for local Mihomo caches.
  http  Render http-based proxy-providers from environment variables.

Env for http mode:
  SAKURACAT_URL  Required if SakuraCat should be included
  CORDCLOUD_URL  Required if CordCloud should be included
  IKUUU_URL      Optional
EOF
}

provider_block_common() {
  cat <<'EOF'
    payload: []
    interval: 43200
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
EOF
}

render_file_provider() {
  local name="$1"
  local path="$2"
  cat <<EOF
  ${name}:
    type: file
    path: "${path}"
$(provider_block_common)
EOF
}

render_http_provider() {
  local name="$1"
  local path="$2"
  local url="$3"
  cat <<EOF
  ${name}:
    type: http
    url: "${url}"
    path: "${path}"
$(provider_block_common)
EOF
}

render_file_mode() {
  cat <<'EOF'
proxy-providers:
EOF
  render_file_provider "iKuuu" "./providers/iKuuu_V2.yaml"
  render_file_provider "SakuraCat" "./providers/SakuraCat.yaml"
  render_file_provider "CordCloud" "./providers/CordCloud.yaml"
}

render_http_mode() {
  local emitted=0
  cat <<'EOF'
proxy-providers:
EOF

  if [[ -n "${IKUUU_URL:-}" ]]; then
    render_http_provider "iKuuu" "./providers/iKuuu_V2.yaml" "${IKUUU_URL}"
    emitted=1
  fi
  if [[ -n "${SAKURACAT_URL:-}" ]]; then
    render_http_provider "SakuraCat" "./providers/SakuraCat.yaml" "${SAKURACAT_URL}"
    emitted=1
  fi
  if [[ -n "${CORDCLOUD_URL:-}" ]]; then
    render_http_provider "CordCloud" "./providers/CordCloud.yaml" "${CORDCLOUD_URL}"
    emitted=1
  fi

  if [[ "${emitted}" -eq 0 ]]; then
    echo "No provider URLs supplied for http mode." >&2
    exit 1
  fi
}

main() {
  local mode="${1:-}"
  local output="${2:-}"

  if [[ -z "${mode}" || -z "${output}" ]]; then
    usage >&2
    exit 1
  fi

  case "${mode}" in
    file)
      {
        echo "# Generated by scripts/render-clash-config.sh"
        render_file_mode
        echo
        cat "${TEMPLATE}"
      } > "${output}"
      ;;
    http)
      {
        echo "# Generated by scripts/render-clash-config.sh"
        render_http_mode
        echo
        cat "${TEMPLATE}"
      } > "${output}"
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
